import test from 'node:test';
import assert from 'node:assert/strict';
import { Store } from '../src/db.js';
import { Collector } from '../src/collect.js';
import { attendance, csv, roleReport, userReport, inactiveCandidates } from '../src/reports.js';
import { createEvent, updateEvent, correctAttendance, parseApollo } from '../src/events.js';
import { localMidnight, period, union } from '../src/time.js';
import { commands } from '../src/commands.js';

const base=Date.parse('2026-09-16T00:00:00Z');
function setup(){const db=new Store(':memory:');db.ensureGuild('g',base);const collector=new Collector(db);return {db,collector};}
function v(c:Collector,user:string,channel:string|null,at:number,extra:Partial<{selfDeaf:boolean;afk:string|null} >={}){c.voiceUpdate({guild:'g',user,channel,parent:null,selfDeaf:extra.selfDeaf??false,bot:false,afk:extra.afk??null,at});}
test('messages deduplicate and rate cap without content',()=>{const {db,collector}=setup();db.setConfig('g',{...db.config('g'),participationCap:2});for(let i=0;i<4;i++)collector.message({guild:'g',id:String(i),user:'u',channel:'c',parent:null,category:null,at:base+i*1000,bot:false,webhook:false});collector.message({guild:'g',id:'0',user:'u',channel:'c',parent:null,category:null,at:base,bot:false,webhook:false});const r=userReport(db,'g','u',base,base+60_000,base+60_000);assert.equal(r.messages,4);assert.equal(r.participation,2);db.close();});
test('voice occupancy, moves, AFK and self deafen split observed intervals',()=>{const {db,collector}=setup();db.setConfig('g',{...db.config('g'),requireTwoHumans:true,excludeSelfDeaf:true});v(collector,'a','c',base);v(collector,'b','c',base+10_000);v(collector,'a','c',base+20_000,{selfDeaf:true});v(collector,'a','d',base+30_000);v(collector,'b','c',base+40_000,{afk:'c'});v(collector,'a',null,base+50_000);v(collector,'b',null,base+50_000);const a=userReport(db,'g','a',base,base+50_000,base+50_000),b=userReport(db,'g','b',base,base+50_000,base+50_000);assert.equal(a.connectedMs,50_000);assert.equal(a.qualifyingMs,10_000);assert.equal(b.qualifyingMs,20_000);assert.equal(a.sessions,2);db.close();});
test('presence deduplicates and restart stops at checkpoint',()=>{const {db,collector}=setup();collector.presence({guild:'g',user:'u',games:['Arma Reforger'],bot:false,at:base});collector.presence({guild:'g',user:'u',games:['Arma Reforger'],bot:false,at:base+1000});db.checkpoint(base+10_000);db.recover(base+20_000);const r=userReport(db,'g','u',base,base+30_000,base+30_000);assert.equal(r.gameMs,10_000);assert.equal(r.coverage.gaps.length,1);db.close();});
test('attendance uses union, event boundaries and separate correction',()=>{const {db}=setup();db.segment('g','u','voice',base,base+30_000,true,'c');db.segment('g','u','voice',base+20_000,base+50_000,true,'d');const id=createEvent(db,'g','admin',{name:'Drill',start:base+10_000,end:base+40_000,channels:['c','d'],minimumMinutes:1},base);let r=attendance(db,'g',id,base+60_000);assert.equal(r.rows[0]?.measuredMs,30_000);assert.equal(r.rows[0]?.metMinimum,false);correctAttendance(db,'g',id,'u',1,'admin','Connection issue',base+70_000);r=attendance(db,'g',id,base+70_000);assert.equal(r.rows[0]?.measuredMs,30_000);assert.equal(r.rows[0]?.adjustmentMinutes,1);assert.equal(r.rows[0]?.metMinimum,true);const changed=updateEvent(db,'g',id,'admin',{end:base+50_000},'Extended',base+80_000);assert.equal(changed,true);assert.equal(attendance(db,'g',id,base+80_000).rows[0]?.measuredMs,40_000);db.close();});
test('guild isolation, role zeros, deletion and CSV injection',()=>{const {db,collector}=setup();collector.message({guild:'g',id:'m',user:'u',channel:'c',parent:null,category:null,at:base,bot:false,webhook:false});db.ensureGuild('other',base);assert.equal(userReport(db,'other','u',base,base+1000,base+1000).messages,0);const role=roleReport(db,'g',['u','zero'],base,base+1000,base+1000);assert.equal(role.rows.length,2);assert.equal(role.totals.active,1);assert.match(csv([['=SUM(1,2)']]),/^\uFEFF"'=SUM/);db.deleteMember('g','u');assert.equal(userReport(db,'g','u',base,base+1000,base+1000).messages,0);db.close();});
test('Apollo post parse and duplicate occurrence guard',()=>{const {db}=setup();const p=parseApollo({embeds:[{title:'Operation',description:'Brief',fields:[{name:'Start',value:'<t:1789603200:F>'},{name:'End',value:'<t:1789606800:F>'}]}]});assert.equal(p.name,'Operation');assert.equal(p.start,1789603200000);const e={name:p.name!,start:p.start!,end:p.end!,channels:['c'],minimumMinutes:10,source:'apollo' as const,sourceMessageId:'post'};createEvent(db,'g','admin',e,base);assert.throws(()=>createEvent(db,'g','admin',e,base));createEvent(db,'g','admin',{...e,sourceMessageId:'next-post'},base);db.close();});
test('DST calendar boundaries are 23 and 25 hours',()=>{const spring=localMidnight('2026-03-08','America/New_York'),springNext=localMidnight('2026-03-09','America/New_York');assert.equal(springNext-spring,23*3_600_000);const fall=localMidnight('2026-11-01','America/New_York'),fallNext=localMidnight('2026-11-02','America/New_York');assert.equal(fallNext-fall,25*3_600_000);assert.equal(period(spring+12*3_600_000,1,'America/New_York').end,springNext);assert.equal(union([[0,10],[5,20]]),20);});
test('LOA, excluded role, newcomer and observed activity are separate',()=>{const {db,collector}=setup();db.setConfig('g',{...db.config('g'),loaRoles:['loa'],excludedRoles:['excluded'],newcomerGraceDays:7});collector.message({guild:'g',id:'one',user:'active',channel:'c',parent:null,category:null,at:base+1000,bot:false,webhook:false});const members=['active','quiet','leave','new','excluded'].map(id=>({id,roles:id==='leave'?['loa']:id==='excluded'?['excluded']:[],joinedAt:id==='new'?base:base-20*86_400_000}));const result=inactiveCandidates(db,'g',members,base,base+86_400_000,base+86_400_000);assert.deepEqual(result.ids,['quiet']);db.close();});
test('retention trims source records and makes old calculations incomplete',()=>{const {db}=setup();db.setConfig('g',{...db.config('g'),retentionDays:1});db.message('g','old','u','c',null,base);db.segment('g','u','voice',base,base+3600_000,true,'c');db.prune('g',base+3*86_400_000);assert.equal(userReport(db,'g','u',base,base+86_400_000,base+3*86_400_000).messages,0);assert.equal(userReport(db,'g','u',base,base+86_400_000,base+3*86_400_000).qualifyingMs,0);db.close();});
test('slash definitions are guild-only and default to Administrator',()=>{for(const c of commands){const json=c.toJSON();assert.deepEqual(json.contexts,[0]);assert.equal(json.default_member_permissions,'8');}});
